const redirects = [
  {
    source: "/category/:slug*",
    destination: "/clubleben/news",
  },
  {
    source: "/tag/:slug*",
    destination: "/clubleben/news",
  },
  {
    source: "/news",
    destination: "/clubleben/news",
  },
  {
    source: "/blog",
    destination: "/clubleben/news",
  },
  {
    source: "/aktuelles",
    destination: "/clubleben/news",
  },
  {
    source: "/elterntraining",
    destination: "/golferlernen/elterntraining",
  },
  {
    source: "/golfpartner",
    destination: "/partner",
  },
  {
    source: "/kooperationen",
    destination: "/partner",
  },
  {
    source: "/vorstand",
    destination: "/ueber-uns/team",
  },
  {
    source: "/mosel-course",
    destination: "/golfanlage/mosel-course",
  },
  {
    source: "/eifel-course",
    destination: "/golfanlage/eifel-course",
  },
  {
    source: "/footgolf-3",
    destination: "/golfanlage/footgolf",
  },
  {
    source: "/dgv-platzreife",
    destination: "/golferlernen/platzreife",
  },
  {
    source: "/kontakt",
    destination: "/ueber-uns/kontakt",
  },
  {
    source: "/mitgliedschaft",
    destination: "/clubleben/mitgliedschaft",
  },
  {
    source: "/preisuebersicht",
    destination: "/clubleben/mitgliedschaft",
  },
  {
    source: "/schnupperkurs",
    destination: "/golferlernen/schnupperkurs",
  },
  {
    source: "/golf-ag",
    destination: "/jugend",
  },
  {
    source: "/jugendtraining",
    destination: "/jugend",
  },
  {
    source: "/camps",
    destination: "/jugend",
  },
  {
    source: "/platzinformationen",
    destination: "/golfanlage/platzinformationen",
  },
];

const simpleRedirects = [
  "/events/:slug*",
  "/mec-category/:slug*",
  "/shop(-2)?/:slug*",
  "/veranstaltungen",
  "/elektro-caddy-boxen",
  "/roompot-open",
  "/entwaesserung",
  "/gelungenes-turnier",
  "/bambini-jugendtraining",
  "/ak-65-mannschaft",
  "/matchplay",
  "/preis-des-praesidenten-2021",
  "/tatort-golfplatz",
  "/golf-jugendcamp-2021",
  "/80-jahre-golf",
  "/golffreunde-tee-1",
  "/calendonia-puttliga",
  "/gelungenes-benefiz-turnier",
  "/2-benefiz-turnier-geglueckt",
  "/neue-golfpartner",
  "/nina-hoelzenbein-bei-den-dt-meisterschaften",
  "/clubmeister-2021-gekuert",
  "/mitgliederversammlung-2",
  "/dreifacher-triumph",
  "/dt-krebshilfe-regionalfinale",
  "/lgv-junior-trophy",
  "/spendenuebergabe-an-den-htc-bad-neuenahr",
  "/bambini-clubmeisterschaften-2021",
  "/mens-day-golfer-on-tour",
  "/lgv-praesidentencup",
  "/gc-cochem-stellt-den-bundessieger",
  "/neue-vierer-clubmeister-ermittelt",
  "/bayrischer-abend-turnier",
  "/ninas-fabelrunde",
  "/neuer-sportkreisjugendwart",
  "/mens-day-golfer",
  "/eifel-marathon",
  "/vizemeisterin",
  "/gc-cochem-stellt-erneut-die-bundessieger",
  "/top-platzierung-beim-finale",
  "/wir-machen-den-weg-frei",
  "/eine-echte-sauerei",
  "/son-servera-neuer-partnerclub",
  "/mygolf-de-wird-zu-golf-de",
  "/saisonstart-2022",
  "/indoor-golf",
  "/bundeswehr-auf-ins-gelaende",
  "/saisoneroeffnung",
  "/vorher-nachher-effekt",
  "/mitgliederversammlung",
  "/attraktivitaet-erkannt",
  "/gelungener-turnierauftakt",
  "/erste-top-platzierung",
  "/neue-mitglieder-neue-partner",
  "/begeisterung-bei-der-jhv",
  "/regen-schnee-matsch",
  "/begeisterung-fuer-indoor-golf",
  "/malta-junior-golf-open",
  "/praktikum-beim-gc-cochem",
  "/glueckwuensche",
  "/mens-day-tour-2022",
  "/wer-kriegt-den-pokal",
  "/mehr-als-ein-ausflug",
  "/auf-erfolgskurs",
  "/spitzenposition-bei-der-ak-50",
  "/was-macht-eigentlich-unsere-nina",
  "/der-mayener-jung-eine-erfolgsgeschichte",
  "/newel-cup-eine-heisse-sache",
  "/vom-aschenputtel-zur-prinzessin",
  "/coc-schlaegt-myk",
  "/neue-partnerschaft",
  "/gelungenes-heimspiel-der-ak-50-ii",
  "/rekordbeteiligung-beim-putten",
  "/in-schlagweite",
  "/der-traum-lebt",
  "/greenkeepers-rache",
  "/sehen-hoeren",
  "/zurueck-zur-alten-staerke",
  "/der-marathon-mann",
  "/alles-nach-plan",
  "/lgv-junior-trophy-2",
  "/praesident-ruft-alle-kommen",
  "/roompot-open-2",
  "/grossartiger-erfolg-fuer-nina",
  "/aufstieg-fuer-die-herren-ak-50-i",
  "/neue-clubmeisterin-2022-ermittelt",
  "/hole-in-one-fuer-adriane-koester",
  "/teilnahmme-am-bundesfinale",
  "/erneuter-bundessieg",
  "/bambini-clubmeisterschaften",
  "/golfen-fuer-einen-guten-zweck",
  "/das-finale-der-besten",
  "/deutsche-vizemeisterin",
  "/fabelhafte-fabelrunde",
  "/gelungener-abschluss-der-ak-65-mannschaft",
  "/aus-der-traum",
  "/feuchtfroehliches-turnier",
  "/saisonausklang",
  "/volles-haus",
  "/unsere-nina-hat-es-geschafft",
  "/viele-haende-schnelles-ende",
  "/glueckwunsch-felix",
  "/faites-votre-jeu",
  "/hole-in-one",
  "/nina-on-tour",
  "/dankeschoen-turnier",
  "/harmonische-mitgliederversammlung",
  "/fitting-und-demo-tag",
  "/tag-der-offenen-tuer",
  "/gegolft-gehofft-geholfen",
  "/dreimal-ist-goettlich",
  "/erstes-ligaspiel-ak50-i",
  "/erstes-spiel-erster-sieg",
  "/schlag-um-schlag",
  "/es-ist-angerichtet",
  "/wthc-wer-steckt-dahinter",
  "/putten-und-seine-vorteile",
  "/und-der-zweite-streich-folgt-sogleich",
  "/roompot-open-3",
  "/gut-geputtet-ist-halb-gewonnen",
  "/freundschaften-pflegen",
  "/trockene-angelegenheit",
  "/das-rough",
  "/matchplay-2023",
  "/spitzenplatz-behauptet",
  "/golf-genuss",
  "/praesidentencup-2023",
  "/er-kam-sah-und-siegte",
  "/40-neue-botschafter",
  "/geschafft",
  "/5-std-53-min-28-sec",
  "/sample-page",
  "/mens-day",
  "/golfanlage",
  "/golfschule",
  "/kalender",
  "/gaestemeinungen",
  "/mannschaften-2",
  "/platzregeln",
  "/mitgliederbereich",
  "/newsletter",
  "/galerie",
  "/shop",
  "/warenkorb",
  "/kasse",
  "/mein-konto",
  "/spielordnung",
  "/protokolle",
  "/agb",
  "/widerrufsbelehrung",
  "/versandarten",
  "/bezahlmoeglichkeiten",
  "/kooperationen-2",
  "/gruppentraining",
  "/bundeswehr",
  "/indoor-golf",
  "/trackman",
  "/fotowettbewerb-2022",
  "/kalender-2",
  "/turnieruebersicht",
  "/turnierdurchfuehrung",
  "/spielberichte-ak50-i",
  "/herren-ak-50-i",
  "/colibri-10706",
  "/herren-ak-65",
  "/ladies-day-4",
  "/herren",
  "/colibri-13094",
  "/aufbaukurs-2024",
  "/downloads",
];

export const getRedirects = () => [
  ...redirects.map(({ source, destination, permanent }) => ({
    source,
    destination: destination || "/",
    permanent: permanent || true,
  })),
  ...simpleRedirects.map((source) => ({
    source,
    destination: "/",
    permanent: true,
  })),
];
